"""
Annotation Export Utilities

Converts SAM 3 annotations to various formats for training and evaluation.
Supports: YOLO, COCO JSON, semantic segmentation masks.
"""

import json
import logging
from enum import Enum
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime
import numpy as np
from PIL import Image
import cv2

from .sam3_annotator import AnnotationResult

logger = logging.getLogger(__name__)


class ExportFormat(Enum):
    """Supported annotation export formats"""
    YOLO_TXT = "yolo_txt"  # One .txt per image, class_id x y w h
    COCO_JSON = "coco_json"  # Single JSON with all annotations
    SEGMENTATION_MASKS = "seg_masks"  # PNG masks for semantic segmentation
    INSTANCE_MASKS = "instance_masks"  # PNG masks with instance IDs


class AnnotationExporter:
    """
    Export SAM 3 annotations to various training formats.

    Example:
        >>> exporter = AnnotationExporter(output_dir="data/annotations")
        >>> exporter.export_yolo(
        ...     image_paths=["img1.jpg", "img2.jpg"],
        ...     annotations=annotations_dict
        ... )
    """

    def __init__(self, output_dir: Path):
        """
        Initialize exporter.

        Args:
            output_dir: Root directory for exported annotations
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Annotation exporter initialized: {self.output_dir}")

    def export_yolo(
        self,
        image_paths: List[Path],
        annotations: Dict[str, List[AnnotationResult]],
        split: str = "train"
    ) -> Path:
        """
        Export annotations in YOLO format.

        Creates structure:
        output_dir/yolo_format/
            images/
                train/
                val/
            labels/
                train/
                val/
            dataset.yaml

        Args:
            image_paths: List of image file paths
            annotations: Dict mapping image path → annotations
            split: Dataset split ('train', 'val', 'test')

        Returns:
            Path to dataset.yaml
        """
        logger.info(f"Exporting YOLO format ({split} split)...")

        # Create directories
        yolo_dir = self.output_dir / "yolo_format"
        images_dir = yolo_dir / "images" / split
        labels_dir = yolo_dir / "labels" / split

        images_dir.mkdir(parents=True, exist_ok=True)
        labels_dir.mkdir(parents=True, exist_ok=True)

        # Copy images and create label files
        for image_path in image_paths:
            image_path = Path(image_path)
            image_key = str(image_path)

            # Get image dimensions
            with Image.open(image_path) as img:
                img_width, img_height = img.size

            # Copy image
            dest_image = images_dir / image_path.name
            if not dest_image.exists():
                import shutil
                shutil.copy(image_path, dest_image)

            # Create label file
            label_file = labels_dir / f"{image_path.stem}.txt"

            if image_key in annotations:
                with open(label_file, 'w') as f:
                    for ann in annotations[image_key]:
                        yolo_line = ann.get_yolo_format(img_width, img_height)
                        f.write(yolo_line + '\n')
            else:
                # Create empty label file (no detections)
                label_file.touch()

        # Create dataset.yaml
        yaml_path = yolo_dir / "dataset.yaml"
        self._create_dataset_yaml(yolo_dir, yaml_path)

        logger.info(f"YOLO export complete: {len(image_paths)} images")
        return yaml_path

    def _create_dataset_yaml(self, yolo_dir: Path, yaml_path: Path):
        """Create YOLO dataset.yaml configuration file"""
        # Extract class names from annotations
        class_names = {
            0: 'car',
            1: 'truck',
            2: 'bus',
            3: 'motorcycle',
            4: 'bicycle',
            5: 'person'
        }

        yaml_content = f"""# TrafficLLM YOLO Dataset
# Auto-generated by SAM3Annotator on {datetime.now().isoformat()}

path: {yolo_dir.absolute()}  # Dataset root
train: images/train  # Train images
val: images/val  # Validation images
test: images/test  # Test images (optional)

# Classes
names:
"""

        for class_id, class_name in sorted(class_names.items()):
            yaml_content += f"  {class_id}: {class_name}\n"

        with open(yaml_path, 'w') as f:
            f.write(yaml_content)

        logger.info(f"Created dataset.yaml: {yaml_path}")

    def export_coco(
        self,
        image_paths: List[Path],
        annotations: Dict[str, List[AnnotationResult]],
        categories: Optional[List[Dict]] = None
    ) -> Path:
        """
        Export annotations in COCO JSON format.

        Args:
            image_paths: List of image file paths
            annotations: Dict mapping image path → annotations
            categories: List of category dicts (id, name). Auto-generated if None.

        Returns:
            Path to COCO JSON file
        """
        logger.info("Exporting COCO JSON format...")

        # Default categories
        if categories is None:
            categories = [
                {'id': 0, 'name': 'car', 'supercategory': 'vehicle'},
                {'id': 1, 'name': 'truck', 'supercategory': 'vehicle'},
                {'id': 2, 'name': 'bus', 'supercategory': 'vehicle'},
                {'id': 3, 'name': 'motorcycle', 'supercategory': 'vehicle'},
                {'id': 4, 'name': 'bicycle', 'supercategory': 'vehicle'},
                {'id': 5, 'name': 'person', 'supercategory': 'person'}
            ]

        # Build COCO structure
        coco_dict = {
            'info': {
                'description': 'TrafficLLM Dataset',
                'version': '1.0',
                'year': datetime.now().year,
                'contributor': 'SAM3Annotator',
                'date_created': datetime.now().isoformat()
            },
            'licenses': [],
            'images': [],
            'annotations': [],
            'categories': categories
        }

        annotation_id = 1

        for image_id, image_path in enumerate(image_paths, start=1):
            image_path = Path(image_path)
            image_key = str(image_path)

            # Get image info
            with Image.open(image_path) as img:
                img_width, img_height = img.size

            # Add image entry
            coco_dict['images'].append({
                'id': image_id,
                'file_name': image_path.name,
                'width': img_width,
                'height': img_height,
                'date_captured': datetime.now().isoformat()
            })

            # Add annotations
            if image_key in annotations:
                for ann in annotations[image_key]:
                    # Convert mask to polygon
                    polygon = self._mask_to_polygon(ann.mask) if ann.mask is not None else []

                    # Calculate bounding box area
                    x1, y1, x2, y2 = ann.box
                    bbox_width = x2 - x1
                    bbox_height = y2 - y1
                    area = bbox_width * bbox_height

                    coco_dict['annotations'].append({
                        'id': annotation_id,
                        'image_id': image_id,
                        'category_id': ann.class_id,
                        'bbox': [x1, y1, bbox_width, bbox_height],  # COCO format: [x, y, w, h]
                        'area': float(area),
                        'segmentation': polygon,
                        'iscrowd': 0,
                        'score': ann.score
                    })

                    annotation_id += 1

        # Save COCO JSON
        coco_path = self.output_dir / "coco_annotations.json"
        with open(coco_path, 'w') as f:
            json.dump(coco_dict, f, indent=2)

        logger.info(f"COCO export complete: {coco_path}")
        return coco_path

    def _mask_to_polygon(self, mask: np.ndarray) -> List[List[float]]:
        """
        Convert binary mask to polygon coordinates (COCO segmentation format).

        Args:
            mask: Binary mask (H, W)

        Returns:
            List of polygon coordinates [[x1, y1, x2, y2, ...]]
        """
        if mask is None:
            return []

        # Convert to uint8
        mask_uint8 = (mask * 255).astype(np.uint8)

        # Find contours
        contours, _ = cv2.findContours(
            mask_uint8,
            cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE
        )

        # Convert contours to polygon format
        polygons = []
        for contour in contours:
            if len(contour) >= 3:  # Need at least 3 points for polygon
                # Flatten and convert to list
                polygon = contour.flatten().tolist()
                polygons.append(polygon)

        return polygons

    def export_segmentation_masks(
        self,
        image_paths: List[Path],
        annotations: Dict[str, List[AnnotationResult]],
        mode: str = "semantic"
    ) -> Path:
        """
        Export segmentation masks as PNG images.

        Args:
            image_paths: List of image file paths
            annotations: Dict mapping image path → annotations
            mode: "semantic" (class IDs) or "instance" (unique instance IDs)

        Returns:
            Path to masks directory
        """
        logger.info(f"Exporting {mode} segmentation masks...")

        masks_dir = self.output_dir / f"{mode}_masks"
        masks_dir.mkdir(parents=True, exist_ok=True)

        for image_path in image_paths:
            image_path = Path(image_path)
            image_key = str(image_path)

            if image_key not in annotations or not annotations[image_key]:
                continue

            # Get image dimensions
            with Image.open(image_path) as img:
                img_width, img_height = img.size

            # Create combined mask
            if mode == "semantic":
                # Semantic: Each pixel has class ID
                combined_mask = np.zeros((img_height, img_width), dtype=np.uint8)

                for ann in annotations[image_key]:
                    if ann.mask is not None:
                        # Resize mask if needed
                        if ann.mask.shape != (img_height, img_width):
                            mask_resized = cv2.resize(
                                ann.mask.astype(np.uint8),
                                (img_width, img_height),
                                interpolation=cv2.INTER_NEAREST
                            )
                        else:
                            mask_resized = ann.mask.astype(np.uint8)

                        # Assign class ID where mask is True
                        combined_mask[mask_resized > 0] = ann.class_id + 1  # +1 so background=0

            elif mode == "instance":
                # Instance: Each pixel has unique instance ID
                combined_mask = np.zeros((img_height, img_width), dtype=np.uint16)

                for instance_id, ann in enumerate(annotations[image_key], start=1):
                    if ann.mask is not None:
                        # Resize mask if needed
                        if ann.mask.shape != (img_height, img_width):
                            mask_resized = cv2.resize(
                                ann.mask.astype(np.uint8),
                                (img_width, img_height),
                                interpolation=cv2.INTER_NEAREST
                            )
                        else:
                            mask_resized = ann.mask.astype(np.uint8)

                        # Assign instance ID where mask is True
                        combined_mask[mask_resized > 0] = instance_id

            # Save mask
            mask_path = masks_dir / f"{image_path.stem}.png"
            Image.fromarray(combined_mask).save(mask_path)

        logger.info(f"Segmentation masks exported: {masks_dir}")
        return masks_dir

    def export_summary_report(
        self,
        annotations: Dict[str, List[AnnotationResult]],
        output_path: Optional[Path] = None
    ) -> Path:
        """
        Generate summary report of annotations.

        Args:
            annotations: Dict mapping image path → annotations
            output_path: Path to save report. Uses default if None.

        Returns:
            Path to report JSON
        """
        if output_path is None:
            output_path = self.output_dir / "annotation_summary.json"

        # Calculate statistics
        total_images = len(annotations)
        total_annotations = sum(len(anns) for anns in annotations.values())

        # Class distribution
        class_counts = {}
        confidence_scores = []

        for anns in annotations.values():
            for ann in anns:
                class_counts[ann.class_name] = class_counts.get(ann.class_name, 0) + 1
                confidence_scores.append(ann.score)

        # Build report
        report = {
            'timestamp': datetime.now().isoformat(),
            'total_images': total_images,
            'total_annotations': total_annotations,
            'annotations_per_image': {
                'mean': total_annotations / total_images if total_images > 0 else 0,
                'min': min(len(anns) for anns in annotations.values()) if annotations else 0,
                'max': max(len(anns) for anns in annotations.values()) if annotations else 0
            },
            'class_distribution': class_counts,
            'confidence_scores': {
                'mean': np.mean(confidence_scores) if confidence_scores else 0,
                'min': float(np.min(confidence_scores)) if confidence_scores else 0,
                'max': float(np.max(confidence_scores)) if confidence_scores else 0,
                'std': float(np.std(confidence_scores)) if confidence_scores else 0
            }
        }

        # Save report
        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2)

        logger.info(f"Summary report saved: {output_path}")
        logger.info(f"  Total images: {total_images}")
        logger.info(f"  Total annotations: {total_annotations}")
        logger.info(f"  Class distribution: {class_counts}")

        return output_path
